name: Update Trophy
on:
  schedule:
    - cron: "0 0 * * *" # Daily midnight update
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch GitHub data and update SVG
        run: |
          node src/fetchData.js
          node src/generateSVG.js

      - name: Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add trophy.svg data.json
          git commit -m "Auto-update trophy"
          git push
